apiVersion: v1
kind: ConfigMap
metadata:
  name: website-content-v1

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial;text-align:center;margin-top:100px;background:#e8f5e9;">
      <h1 style="font-size:60px;color:green;">Welcome to V1</h1>
      <h2>Argo CD Canary Lab</h2>
    </body>
    </html>